cc.in: Allow overriding stub link failure
Add an undocumented RUMPRUN_STUBLINK toggle to always succeed in the
stub link phase, so that I can build clock_test with -DBMK without
having to modify the generated cc each time.

diff --git a/app-tools/cc.in b/app-tools/cc.in
--- a/app-tools/cc.in
+++ b/app-tools/cc.in
@@ -86,8 +86,12 @@ ferment)
 	    -specs=!APPTOOLS_DIR!/specs-stub \
 	    ${OUTFILE} -o /dev/null
 	if [ $? -ne 0 ]; then
-		[ -f "${OUTFILE}" ] && rm -f ${OUTFILE}
-		die
+		if [ "${RUMPRUN_STUBLINK}" = "succeed" ]; then
+			echo "$0: warning: stub link failed, ignoring" 1>&2
+		else
+			[ -f "${OUTFILE}" ] && rm -f ${OUTFILE}
+			die
+		fi
 	fi
 
 	# Some build systems insist that the output looks like an executable.
