Remove check for __RuMpRuN_baked__
Problems with it:
1) breaks naiive strip (you need strip -K __RuMpSAdfdsaf)
2) prevents from using gzipped binaries as rumprun arguments
3) in its current form, catches only a small set of errors (not
   e.g. trying to rumprun xen a binary baked for hw)

At least 1 and 2 should be fixed before possibly reintroducing this
safety net, but for now we'll just assume that the user is not making
mistakes.

diff --git a/app-tools/rumprun b/app-tools/rumprun
--- a/app-tools/rumprun
+++ b/app-tools/rumprun
@@ -141,11 +141,8 @@ setuptmpdir ()
 
 check_app ()
 {
-	[ -f "$1" ] || die "file not found: $1"
 
-	if ! grep -q __RuMpRuN_baked__ "$1"; then
-		die "$1: not a rumprun unikernel (did you forget rumpbake?)"
-	fi
+	[ -f "$1" ] || die "file not found: $1"
 }
 
 store_netspec=usage
