Prevent unrelated env variables from being listed as valid configs
As a side effect, an empty config is now possible (but does not
yet work since rumpconfig hardcodes references to netconfig)

diff --git a/app-tools/rumpbake b/app-tools/rumpbake
--- a/app-tools/rumpbake
+++ b/app-tools/rumpbake
@@ -62,6 +62,20 @@ nuketmpdir ()
 	rm -rf ${nukeme}
 }
 
+ALLCONFIGS=
+addconfig ()
+{
+	[ $# -ge 2 ] || { echo rumpbake.conf error; exit 1; }
+
+	confname=$1
+	toolchain=$2
+	shift 2
+
+	ALLCONFIGS="${ALLCONFIGS} ${confname}"
+	eval TOOLCHAIN_${confname}=${toolchain}
+	eval CONFIG_${confname}=\"$@\"
+}
+
 APP_TOOLS_DIR=$(dirname $0)
 CONF=${APP_TOOLS_DIR}/rumpbake.conf
 if [ ! -f ${CONF} ]; then
@@ -70,11 +84,9 @@ if [ ! -f ${CONF} ]; then
 fi
 . ${CONF}
 
-CONFIG=
-
 TARGET="${1}"
 if [ "${TARGET}" = "list" ]; then
-	set | sed -ne 's/^CONFIG_\([a-zA-Z0-9_]*\)=.*$/\1/p'
+	echo ${ALLCONFIGS} | xargs -n 1 echo
 	exit 0
 fi
 
@@ -87,13 +99,17 @@ shift 2
 # Santize the config argument passed in to remove shell
 # metacharacters
 config="$(echo ${TARGET} | sed -e 's/-/_/g' -e 's/[^A-Za-z0-9_]//g')"
+for c in ${ALLCONFIGS}; do
+	[ "$c" = "$config" ] && break
+done
+if [ "$c" != "$config" ]; then
+	echo "rumpbake: error: unsupported config \"$config\""
+	exit 1
+fi
+
 # Sets CONFIG to $(CONFIG_<name>) and CC to $(CC_<name>)
 eval CONFIG="\${CONFIG_${config}}"
 eval TOOLCHAIN="\${TOOLCHAIN_${config}}"
-if [ -z "${CONFIG}" -o -z "${TOOLCHAIN}" ]; then
-	echo "rumpbake: error: Unsupported configuration \`${config}'"
-	usage
-fi
 
 # Parse CONFIG, mapping each component to $LIBS_component and each resulting
 # lib to -l$lib
@@ -125,5 +141,4 @@ done
 
 # Final link using cc to produce the unikernel image.
 ${APP_TOOLS_DIR}/${TOOLCHAIN}-cc \
-	-bake -o ${OUTPUT} ${allobjs} -Wl,--whole-archive ${LIBS} \
-	|| exit 1
+    -bake -o ${OUTPUT} ${allobjs} -Wl,--whole-archive ${LIBS} || exit 1
