Make rumpbake constant over all platforms.
Embed the necessary information to move from a ferment to a baked product
into an ELF note section.  Use that information during baking to determine
where to find the appropriate toolchain from.

diff --git a/app-tools/rumpbake b/app-tools/rumpbake
--- a/app-tools/rumpbake
+++ b/app-tools/rumpbake
@@ -28,6 +28,8 @@
 # rumpbake: script for final stage linking ("baking") of a unikernel image
 #
 
+: ${READELF:=readelf}
+
 if [ "${RUMPRUN_WARNING_STFU}" != 'please' ]; then
 	exec 3>&1 1>&2
 	echo
@@ -37,6 +39,13 @@ if [ "${RUMPRUN_WARNING_STFU}" != 'please' ]; then
 	echo
 	exec 1>&3 3>&-
 fi
+
+die()
+{
+
+	echo ">> ERROR: $*"
+	exit 1
+}
 
 usage ()
 {
@@ -76,6 +85,39 @@ addconfig ()
 	eval CONFIG_${confname}=\"$@\"
 }
 
+getbininfo ()
+{
+
+	# extract bake recipe
+	notesect=.note.rumprun.bakerecipe
+	tuple="$(readelf -p ${notesect} $1 2>/dev/null \
+	    | sed -n 's/.*rumprun_tuple: //p')"
+	[ -n "${tuple}" ] \
+	    || die "Could not extract tuple from $1.  Not a rumprun binary?"
+	tooldir="$(readelf -p ${notesect} $1 2>/dev/null \
+	    | sed -n 's/.*rumprun_tooldir: //p')"
+	[ -n "${tooldir}" ] \
+	    || die "Could not extract tooldir from $1.  Not a rumprun binary?"
+	mycc="$(readelf -p ${notesect} $1 2>/dev/null \
+	    | sed -n 's/.*rumprun_backingcc: //p')"
+	[ -n "${mycc}" ] \
+	    || die "Could not extract cc from $1.  Not a rumprun binary?"
+	mycflags="$(readelf -p ${notesect} $1 2>/dev/null \
+	    | sed -n 's/.*rumprun_cflags: //p')"
+	[ -n "${mycc}" ] \
+	    || die "Could not extract cflags from $1.  Not a rumprun binary?"
+
+	# check that all binaries are consistent
+	[ "${RUMPBAKE_TUPLE:=${tuple}}" = "${tuple}" ] \
+	    || die tuple mismatch in binary ingredients
+	[ "${RUMPBAKE_APPTOOLDIR:=${tooldir}}" = "${tooldir}" ] \
+	    || die tooldir mismatch in binary ingredients
+	[ "${RUMPBAKE_CC:=${mycc}}" = "${mycc}" ] \
+	    || die cc mismatch in binary ingredients
+	[ "${RUMPBAKE_CFLAGS:=${mycflags}}" = "${mycflags}" ] \
+	    || die cflgas mismatch in binary ingredients
+}
+
 APP_TOOLS_DIR=$(dirname $0)
 CONF=${APP_TOOLS_DIR}/rumpbake.conf
 if [ ! -f ${CONF} ]; then
@@ -93,6 +135,15 @@ fi
 OUTPUT="${2}"
 [ $# -gt 2 ] || usage
 shift 2
+
+# We need readelf to extract the ELF note with the baking recipe.
+# Just any readelf will do, but we need one.
+type ${READELF} >/dev/null 2>&1 \
+    || die 'Cannot find ${READELF}. Set $READELF env variable'
+unset RUMPBAKE_CC
+unset RUMPBAKE_TUPLE
+unset RUMPBAKE_CFLAGS
+unset RUMPBAKE_APPTOOLDIR
 
 [ $# -le 8 ] || { echo '>> max 8 binaries supported currently' ; exit 1; }
 
@@ -128,11 +179,9 @@ trap nuketmpdir 0 INT TERM
 objnum=1
 allobjs=
 for f in "$@"; do
-	if ! grep -q __RuMpRuN_fermented__ ${f}; then
-		echo "rumpbake: error: ${f}: not a rumprun relocatable object"
-		exit 1
-	fi
-	${APP_TOOLS_DIR}/!GNUPLATFORM!-objcopy				\
+	getbininfo ${f}
+
+	${RUMPBAKE_APPTOOLDIR}/${RUMPBAKE_TUPLE}-objcopy		\
 	    --redefine-sym main=rumpbake_main${objnum}			\
 	    ${f} ${TMPDIR}/tmp${objnum}.obj
 	allobjs="${allobjs} ${TMPDIR}/tmp${objnum}.obj"
@@ -140,7 +189,8 @@ for f in "$@"; do
 done
 
 # Final link using cc to produce the unikernel image.
-!CC! !CFLAGS! -specs=!APPTOOLS_DIR!/${TOOLCHAIN}-specs-bake		\
+${RUMPBAKE_CC} ${RUMPBAKE_CFLAGS}					\
+    -specs=${RUMPBAKE_APPTOOLDIR}/${TOOLCHAIN}-specs-bake		\
     -Wl,--defsym=__RuMpRuN_baked__=0 -o ${OUTPUT} ${allobjs}		\
     -Wl,--whole-archive ${LIBS} || exit 1
 
